# Generated by Django 3.2.5 on 2021-09-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='daily life', max_length=255),
        ),
    ]
